### ISSUE TITLE
Application crashed on Ubuntu

### ISSUE THREAD

**Issue by krissch19** [acjim/AcmacsDesktop#150] opened 2015-10-29 12:00 UTC
I reloaded the application. No file was open. I went to File -> Open..., Before the dialogue could come up the application crashed. 
The following is the console output:

[3518:1029/215419:INFO:CONSOLE(216)] ""(node) warning: possible EventEmitter memory leak detected. %d %s listeners added. Use emitter.setMaxListeners() to increase limit." "close"", source: events.js (216)
[3518:1029/215420:WARNING:crash_handler_host_linux.cc(289)] Could not translate tid - assuming crashing thread is thread group leader; syscall_supported=1
[3592:1029/215420:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 2147483649, remote ID 3)
[3592:1029/215420:WARNING:channel.cc(553)] Failed to send message to ack remove remote endpoint (local ID 1, remote ID 1)

**Comment by jidel** [comment] 2015-10-29 12:04
duplicate of #136

**Closed by jidel** 2015-10-29 12:04 UTC
Labels: bug, duplicate
