### ISSUE TITLE
Unexpected Change in Color After Disabling

### ISSUE THREAD

**Issue by idrissou** [acjim/AcmacsDesktop#235] opened 2016-01-11 14:22 UTC
Trying to find where this came from. 
It seems when disabling/reenabling, the nodes change colors
![screenshot from 2016-01-11 12 57 19](https://cloud.githubusercontent.com/assets/12066194/12235896/227cc0ac-b877-11e5-9995-42279d0f98db.png)

**Comment by idrissou** [comment] 2016-01-11 14:31
We didn't have this problem before. It seems a new functionality is affecting it:
https://github.com/acjim/AcmacsDesktop/tree/DisconnectPoints

**Comment by idrissou** [comment] 2016-01-11 14:48
@jidel: I think your last update for the plugin is responsible for this. The color don't chnage in the last branch :) https://github.com/acjim/AcmacsDesktop/tree/DisconnectPoints

**Comment by jidel** [comment] 2016-01-11 16:09
Error must be at your end. The current master branch is working fine for me. (Or try to provide a explanation of what you are doing exactly to get this behaviour)

**Comment by idrissou** [comment] 2016-01-11 16:50
try to select a bunch of nodes and click on disable (no mater which one of the two) and then reenable again, if everything is normal, report to me please.
Rohan and I have the same problem.

**Comment by jidel** [comment] 2016-01-11 16:51
Can't reproduce (I'm on mac):
disabled:
![screen shot 2016-01-11 at 17 51 01](https://cloud.githubusercontent.com/assets/6048968/12240063/f646a3e4-b88b-11e5-9564-0670cea06b2d.jpeg)
Re-enabling:
![screen shot 2016-01-11 at 17 51 06](https://cloud.githubusercontent.com/assets/6048968/12240074/fe0445f0-b88b-11e5-95db-d52e722725da.jpeg)

**Comment by idrissou** [comment] 2016-01-11 16:58
It is working for you apparently @jidel

**Comment by jidel** [comment] 2016-01-11 17:06
Maybe you guys have some modified code not showing up in webstorm

**Comment by idrissou** [comment] 2016-01-12 16:23
I found the reasons that triggers this bug. It is the array color that give only the color value of the first selected node in the array. In this case it is green as the first node is green

**Comment by rohankoid** [comment] 2016-01-13 09:22
Moving this to in progress.

**Comment by idrissou** [comment] 2016-01-14 13:37
Bug Fixed

**Closed** 2016-01-14 13:38 UTC
Labels: bug, Medium
